# ratings_service/Gemfile
source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

# Declare your gem's dependencies in ratings_service.gemspec.
# Bundler will treat runtime dependencies like base dependencies, and
# development dependencies will be added by default to the :development group.
gemspec

# Declare any dependencies that are still in development here instead of in
# your gemspec. These might include edge Rails or gems from your path or
# git repositories.
# gem "rails", github: "rails/rails", branch: "main"

gem 'pg'
gem 'jbuilder'
gem 'rack-cors'